#index:
#    path: /
#    controller: App\Controller\DefaultController::index

site_index:
    path:       /
    controller: App\Controller\HomeController::index

site_login:
    path:       /login/
    controller: App\Controller\UtilisateurController::login

site_signup:
    path:       /signup/
    controller: App\Controller\UtilisateurController::signup

site_estimation:
    path:       /estimation/
    controller: App\Controller\UtilisateurController::estimation
