#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path:       /
    controller: App\Controller\HomeController::index

connexion:
    path:       /connexion/
    controller: App\Controller\SecurityController::connexion

inscription:
    path:       /inscription/
    controller: App\Controller\Registration::register

dashboard:
    path:       /dashboard/
    controller: App\Controller\DashboardController::index

new-project:
    path:       /dashboard/new-project/
    controller: App\Controller\ProjectController::newProject

my-project:
    path:       /dashboard/my-project/{id}/gros-oeuvre
    controller: App\Controller\GrosOeuvreController::view

second-oeuvre:
    path:       /dashboard/my-project/{id}/second-oeuvre
    controller: App\Controller\SecondOeuvreController::view

etude-sol:
    path:       /dashboard/my-project/{id}/gros-oeuvre/etude-sol
    controller: App\Controller\GrosOeuvreController::etudeSol
    
excavation:
    path:       /dashboard/my-project/{id}/gros-oeuvre/excavation
    controller: App\Controller\GrosOeuvreController::excavation
    
vrd:
    path:       /dashboard/my-project/{id}/gros-oeuvre/vrd
    controller: App\Controller\GrosOeuvreController::vrd
    
fondation:
    path:       /dashboard/my-project/{id}/gros-oeuvre/fondations
    controller: App\Controller\GrosOeuvreController::fondation
    
plancher:
    path:       /dashboard/my-project/{id}/gros-oeuvre/plancher
    controller: App\Controller\GrosOeuvreController::plancher
prep-terrain:
    path:       /dashboard/my-project/{id}/gros-oeuvre/prep-terrain
    controller: App\Controller\GrosOeuvreController::PreparationEtAcces
soubassement:
    path:       /dashboard/my-project/{id}/gros-oeuvre/soubassement
    controller: App\Controller\GrosOeuvreController::Soubassement
elevation:
    path:       /dashboard/my-project/{id}/gros-oeuvre/elevation
    controller: App\Controller\GrosOeuvreController::Elevation    

charpente:
    path:       /dashboard/my-project/{id}/gros-oeuvre/charpente
    controller: App\Controller\GrosOeuvreController::charpente
toiture:
    path:       /dashboard/my-project/{id}/gros-oeuvre/toiture
    controller: App\Controller\GrosOeuvreController::toiture
menuiserie:
    path:       /dashboard/my-project/{id}/gros-oeuvre/menuiseries
    controller: App\Controller\GrosOeuvreController::menuiserie
ventilation:
    path:       /dashboard/my-project/{id}/second-oeuvre/ventilation
    controller: App\Controller\SecondOeuvreController::ventilation
climatisation:
    path:       /dashboard/my-project/{id}/second-oeuvre/climatisation
    controller: App\Controller\SecondOeuvreController::climatisation
domotique:
    path:       /dashboard/my-project/{id}/second-oeuvre/domotique
    controller: App\Controller\SecondOeuvreController::domotique    
logout:
    path: /deconnexion
