#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path:       /
    controller: App\Controller\HomeController::index

connexion:
    path:       /connexion/
    controller: App\Controller\SecurityController::connexion

inscription:
    path:       /inscription/
    controller: App\Controller\Registration::register

new-project:
    path:       /dashboard/new-project/
    controller: App\Controller\DashboardController::newProject

dashboard:
    path:       /dashboard/
    controller: App\Controller\DashboardController::index

etude-sol:
    path:       /dashboard/new-project/etude-sol
    controller: App\Controller\DashboardController::etudeSol

logout:
    path: /deconnexion
