#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path:       /
    controller: App\Controller\HomeController::index

connexion:
    path:       /connexion/
    controller: App\Controller\SecurityController::connexion

inscription:
    path:       /inscription/
    controller: App\Controller\SecurityController::inscription

estimation:
    path:       /estimation/
    controller: App\Controller\UtilisateurController::estimation

logout:
    path: /deconnexion
