#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path:       /
    controller: App\Controller\HomeController::index

connexion:
    path:       /connexion/
    controller: App\Controller\SecurityController::connexion

inscription:
    path:       /inscription/
    controller: App\Controller\Registration::register

estimation:
    path:       /estimation/
    controller: App\Controller\DashboardController::estimation

dashboard:
    path:       /dashboard/
    controller: App\Controller\DashboardController::index

logout:
    path: /deconnexion
