#index:
#    path: /
#    controller: App\Controller\DefaultController::index

site_index:
    path:       /
    controller: App\Controller\HomeController::index

site_login:
    path:       /login/
    controller: App\Controller\SecurityController::login

site_signup:
    path:       /signup/
    controller: App\Controller\SecurityController::signup

site_estimation:
    path:       /estimation/
    controller: App\Controller\UtilisateurController::estimation

logout:
    path: /deconnexion
