#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path:       /
    controller: App\Controller\HomeController::index

connexion:
    path:       /connexion/
    controller: App\Controller\SecurityController::connexion

inscription:
    path:       /inscription/
    controller: App\Controller\Registration::register

dashboard:
    path:       /dashboard/
    controller: App\Controller\DashboardController::index

new-project:
    path:       /dashboard/new-project/
    controller: App\Controller\ProjectController::newProject

my-project:
    path:       /dashboard/my-project/{id}
    controller: App\Controller\ProjectController::view

etude-sol:
    path:       /dashboard/my-project/{id}/etude-sol
    controller: App\Controller\ProjectController::etudeSol
    
excavation:
    path:       /dashboard/my-project/{id}/excavation
    controller: App\Controller\ProjectController::excavation
    
vrd:
    path:       /dashboard/my-project/{id}/vrd
    controller: App\Controller\ProjectController::vrd
    
fondation:
    path:       /dashboard/my-project/{id}/fondation
    controller: App\Controller\ProjectController::fondation
    
plancher:
    path:       /dashboard/my-project/{id}/plancher
    controller: App\Controller\ProjectController::plancher

logout:
    path: /deconnexion
